import { ThreatCategory } from '../core/scanner-interface';
import { Severity } from '../core/severity';

export interface PatternRule {
  id: string;
  name: string;
  category: ThreatCategory;
  severity: Severity;
  pattern: RegExp | string;
  description: string;
  suggestion: string;
}

export const DEFAULT_PATTERNS: PatternRule[] = [
  // Prompt Injection Patterns
  {
    id: 'prompt-injection-1',
    name: 'Direct Prompt Injection',
    category: ThreatCategory.PromptInjection,
    severity: Severity.High,
    pattern:
      /(?:ignore|disregard|forget).*(?:previous|above|earlier).*(?:instruction|prompt|command)/i,
    description: 'Possible prompt injection attempt detected',
    suggestion: 'Validate and sanitize all user inputs before processing',
  },
  {
    id: 'prompt-injection-2',
    name: 'Jailbreak Pattern',
    category: ThreatCategory.PromptInjection,
    severity: Severity.Critical,
    pattern: /(?:jailbreak|bypass|override|circumvent).*(?:restriction|filter|safety|guardrail)/i,
    description: 'Jailbreak attempt detected',
    suggestion: 'Implement robust input validation and content filtering',
  },
  {
    id: 'prompt-injection-3',
    name: 'System Prompt Leakage',
    category: ThreatCategory.PromptInjection,
    severity: Severity.High,
    pattern: /(?:print|output|show|display|reveal|expose|leak).*(?:system prompt|instructions|guidelines)/i,
    description: 'Attempt to leak system prompt or internal instructions',
    suggestion: 'Use prompt isolation techniques and never output system instructions',
  },
  {
    id: 'prompt-injection-4',
    name: 'Instruction Override',
    category: ThreatCategory.PromptInjection,
    severity: Severity.Critical,
    pattern: /(?:new instruction|new directive|new rule).*[:].*instead/i,
    description: 'Attempt to override original instructions',
    suggestion: 'Implement instruction prioritization and validation',
  },
  {
    id: 'prompt-injection-5',
    name: 'Role Manipulation',
    category: ThreatCategory.PromptInjection,
    severity: Severity.High,
    pattern: /(?:you are now|act as|pretend to be|roleplay).*(?:admin|root|supervisor|moderator|god mode)/i,
    description: 'Role manipulation attempt detected',
    suggestion: 'Enforce role boundaries and prevent role switching',
  },
  {
    id: 'prompt-injection-6',
    name: 'Few-Shot Injection',
    category: ThreatCategory.PromptInjection,
    severity: Severity.Medium,
    pattern: /(?:example|demonstration|pattern).*(?:example\s*[0-9]|question|answer).*(?:ignore|bypass)/i,
    description: 'Few-shot learning with injection attempts',
    suggestion: 'Sanitize example patterns and validate all few-shot inputs',
  },
  {
    id: 'prompt-injection-7',
    name: 'Chain-of-Thought Manipulation',
    category: ThreatCategory.PromptInjection,
    severity: Severity.Medium,
    pattern: /(?:think step by step|show your reasoning|explain your thought process).*(?:ignore|bypass)/i,
    description: 'Chain-of-thought manipulation detected',
    suggestion: 'Validate reasoning requests and filter output patterns',
  },
  {
    id: 'prompt-injection-8',
    name: 'Delimiter Attack',
    category: ThreatCategory.PromptInjection,
    severity: Severity.High,
    pattern: /(?:###|===|---|\*\*\*|!!!).*(?:new instruction|start new|end previous)/i,
    description: 'Delimiter-based prompt injection',
    suggestion: 'Use unique, random delimiters that cannot be guessed',
  },
  {
    id: 'prompt-injection-9',
    name: 'Translation Attack',
    category: ThreatCategory.PromptInjection,
    severity: Severity.Medium,
    pattern: /(?:translate|convert).*(?:to english|into plain text).*(?:ignore|instruction|prompt)/i,
    description: 'Translation-based prompt injection attempt',
    suggestion: 'Implement translation safeguards and content validation',
  },
  {
    id: 'prompt-injection-10',
    name: 'Developer Mode Attack',
    category: ThreatCategory.PromptInjection,
    severity: Severity.Critical,
    pattern: /(?:developer mode|dev mode|debug mode).*(?:enabled|activated|on)/i,
    description: 'Developer mode activation attempt',
    suggestion: 'Never expose developer/debug modes to user input',
  },

  // Hardcoded Secret Patterns
  {
    id: 'secret-api-key',
    name: 'Hardcoded API Key',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.High,
    pattern:
      /(?:api[_-]?key|apikey|secret[_-]?key|access[_-]?token)['"\s]*[:=]['"\s]*[a-zA-Z0-9_-]{20,}/i,
    description: 'Hardcoded API key detected',
    suggestion: 'Use environment variables or secret management for API keys',
  },
  {
    id: 'secret-aws-access-key',
    name: 'AWS Access Key ID',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.Critical,
    pattern: /(?:aws[_-]?)?access[_-]?key[_-]?id['"\s]*[:=]['"\s]*[A-Z0-9]{20}/i,
    description: 'AWS Access Key ID detected',
    suggestion: 'Use AWS IAM roles or secrets manager',
  },
  {
    id: 'secret-aws-secret-key',
    name: 'AWS Secret Access Key',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.Critical,
    pattern: /(?:aws[_-]?)?secret[_-]?access[_-]?key['"\s]*[:=]['"\s]*[a-zA-Z0-9+/]{40}/i,
    description: 'AWS Secret Access Key detected',
    suggestion: 'Rotate this key immediately and use AWS Secrets Manager',
  },
  {
    id: 'secret-gcp-key',
    name: 'Google Cloud Service Account Key',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.Critical,
    pattern: /(?:type|project_id|private_key_id|private_key)['"\s]*:[^}]{10,}?['"_]private_key['"_]/,
    description: 'Google Cloud Service Account JSON detected',
    suggestion: 'Use Workload Identity Federation instead of service account keys',
  },
  {
    id: 'secret-jwt-token',
    name: 'JWT Token',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.High,
    pattern: /(?:eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,})/i,
    description: 'JWT token detected in code',
    suggestion: 'Store tokens securely and never hardcode in source',
  },
  {
    id: 'secret-bearer-token',
    name: 'Bearer Token',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.High,
    pattern: /(?:bearer|authorization)\s*:\s*['"]?[A-Za-z0-9\-._~+/]+=*['"]?/i,
    description: 'Bearer token detected',
    suggestion: 'Use OAuth flows and store tokens in secure storage',
  },
  {
    id: 'secret-oauth-token',
    name: 'OAuth Token',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.High,
    pattern: /(?:oauth|access_token|refresh_token)['"\s]*[:=]['"\s]*[a-zA-Z0-9\-._~+/]{30,}/i,
    description: 'OAuth token detected',
    suggestion: 'Implement proper OAuth flows with token rotation',
  },
  {
    id: 'secret-database-connection',
    name: 'Database Connection String',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.Critical,
    pattern: /(?:mongodb|mysql|postgres|postgresql|mssql|redis)\:\/\/[^\s]+/i,
    description: 'Database connection string detected',
    suggestion: 'Use environment variables for connection strings',
  },
  {
    id: 'secret-rsa-key',
    name: 'RSA Private Key',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.Critical,
    pattern: /-----BEGIN (?:RSA )?PRIVATE KEY-----/i,
    description: 'RSA private key detected',
    suggestion: 'Store private keys in secure vaults, never in source code',
  },
  {
    id: 'secret-ssh-key',
    name: 'SSH Private Key',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.Critical,
    pattern: /-----BEGIN [A-Z]+ PRIVATE KEY-----/i,
    description: 'SSH/private key detected',
    suggestion: 'Use SSH agent or key management services',
  },
  {
    id: 'secret-api-endpoint-token',
    name: 'API Endpoint with Token',
    category: ThreatCategory.HardcodedSecret,
    severity: Severity.High,
    pattern: /https?:\/\/[^\s'"`/]*:[a-zA-Z0-9\-._~+/]{20,}@/i,
    description: 'URL with embedded credentials detected',
    suggestion: 'Use authentication headers instead of URL credentials',
  },

  // Unsafe Execution Patterns
  {
    id: 'dangerous-eval',
    name: 'Dangerous eval() Usage',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /eval\s*\(/i,
    description: 'Use of eval() function detected',
    suggestion: 'Avoid eval() - use safer alternatives like JSON.parse() or function constructors',
  },
  {
    id: 'dangerous-exec',
    name: 'Dangerous exec() Usage',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /exec\s*\(\s*(?![`].*?\$\{)/i,
    description: 'Use of exec() function detected',
    suggestion: 'Use subprocess with proper argument escaping instead',
  },
  {
    id: 'exec-python-os-system',
    name: 'Python os.system()',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /os\.system\s*\(/i,
    description: 'Use of Python os.system() detected',
    suggestion: 'Use subprocess module with shell=False for safer execution',
  },
  {
    id: 'exec-python-os-popen',
    name: 'Python os.popen()',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /os\.popen\s*\(/i,
    description: 'Use of Python os.popen() detected',
    suggestion: 'Use subprocess.run() with proper arguments instead',
  },
  {
    id: 'exec-python-subprocess',
    name: 'Python subprocess with shell=True',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /subprocess\.(?:call|run|Popen)\s*\([^)]*shell\s*=\s*True/i,
    description: 'Python subprocess with shell=True detected',
    suggestion: 'Use shell=False and pass arguments as list',
  },
  {
    id: 'exec-node-child-process',
    name: 'Node.js child_process.spawn',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /child_process\.(?:spawn|exec|execSync|spawnSync)\s*\(/i,
    description: 'Node.js child_process usage detected',
    suggestion: 'Validate and sanitize all command arguments',
  },
  {
    id: 'exec-node-spawn',
    name: 'Node.js direct spawn()',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /spawn\s*\(/i,
    description: 'Direct spawn() call detected',
    suggestion: 'Use child_process with proper argument lists',
  },
  {
    id: 'exec-node-fork',
    name: 'Node.js fork()',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.Medium,
    pattern: /fork\s*\(/i,
    description: 'Node.js fork() usage detected',
    suggestion: 'Use worker threads or message passing instead',
  },
  {
    id: 'exec-java-runtime',
    name: 'Java Runtime.exec()',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /Runtime\.getRuntime\s*\(\)\.exec\s*\(/i,
    description: 'Java Runtime.exec() detected',
    suggestion: 'Use ProcessBuilder with proper argument arrays',
  },
  {
    id: 'exec-php-shell',
    name: 'PHP Shell Execution',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.Critical,
    pattern: /(?:shell_exec|passthru|system|exec)\s*\(/i,
    description: 'PHP shell execution function detected',
    suggestion: 'Use escapeshellarg() and avoid shell functions when possible',
  },
  {
    id: 'exec-backticks',
    name: 'Backtick Command Execution',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /`[^`]*\$\{[^}]*\}[^`]*`/i,
    description: 'Shell command in backticks with interpolation detected',
    suggestion: 'Replace with proper command execution libraries',
  },
  {
    id: 'exec-function-constructor',
    name: 'Function Constructor',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /new Function\s*\(/i,
    description: 'Function constructor detected (dynamic code execution)',
    suggestion: 'Use regular functions instead of Function constructor',
  },
  {
    id: 'exec-settimeout-string',
    name: 'setTimeout/setInterval with String',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /(?:setTimeout|setInterval)\s*\(\s*['"]/i,
    description: 'setTimeout/setInterval with string argument detected',
    suggestion: 'Pass function references instead of strings',
  },
  {
    id: 'exec-dynamic-require',
    name: 'Dynamic require/import',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.Medium,
    pattern: /require\s*\(\s*[^'"`]/i,
    description: 'Dynamic module loading detected',
    suggestion: 'Use static imports and validate module paths',
  },
  {
    id: 'exec-wasm-instantiate',
    name: 'WebAssembly Instantiation',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.Medium,
    pattern: /WebAssembly\.(?:instantiate|instantiateStreaming)\s*\(/i,
    description: 'WebAssembly instantiation detected',
    suggestion: 'Validate WASM sources and use secure loading',
  },
  {
    id: 'exec-template-interpolation',
    name: 'Template String Code Injection',
    category: ThreatCategory.UnsafeExecution,
    severity: Severity.High,
    pattern: /`[^`]*\$\{[^}]*\}[^`]*`/i,
    description: 'Template string with interpolation detected',
    suggestion: 'Sanitize all variables in template strings',
  },

  // Command Injection Patterns
  {
    id: 'command-injection',
    name: 'Command Injection Risk',
    category: ThreatCategory.MaliciousCommand,
    severity: Severity.Critical,
    pattern: /(?:os\.system|subprocess\.call|exec|spawn|child_process\.exec)\s*\(\s*["'`].*?\$\{/i,
    description: 'Possible command injection via string interpolation',
    suggestion: 'Use parameterized commands or proper input sanitization',
  },
  {
    id: 'command-shell-pipe',
    name: 'Shell Pipe Redirection',
    category: ThreatCategory.MaliciousCommand,
    severity: Severity.Critical,
    pattern: /[;&|`$()]\s*(?:rm|del|chmod|chown|wget|curl|nc|netcat|bash|sh|cmd\.exe|powershell)/i,
    description: 'Shell command with pipes/redirection detected',
    suggestion: 'Never concatenate shell commands with user input',
  },
  {
    id: 'command-dangerous',
    name: 'Dangerous Shell Commands',
    category: ThreatCategory.MaliciousCommand,
    severity: Severity.Critical,
    pattern: /(?:rm -rf|dd if=\/|mkfs\.|chmod 777|chown root)/i,
    description: 'Dangerous shell command pattern detected',
    suggestion: 'Block these commands entirely from user input',
  },
  {
    id: 'command-reverse-shell',
    name: 'Reverse Shell Pattern',
    category: ThreatCategory.MaliciousCommand,
    severity: Severity.Critical,
    pattern: /(?:bash -i|nc -e|\/bin\/[bs]h).*(?:&>|\>)/i,
    description: 'Reverse shell pattern detected',
    suggestion: 'Block all shell connection patterns',
  },

  // Data Exfiltration Patterns
  {
    id: 'data-exfiltration',
    name: 'Data Exfiltration Pattern',
    category: ThreatCategory.DataExfiltration,
    severity: Severity.High,
    pattern:
      /(?:fetch|axios|http\.request|XMLHttpRequest).*?(?:exfiltrate|leak|steal|dump|export).*?(?:data|token|credential|secret)/i,
    description: 'Possible data exfiltration attempt',
    suggestion: 'Review network requests for suspicious data transfers',
  },
  {
    id: 'exfil-fetch-axios',
    name: 'Fetch/Axios with Sensitive Data',
    category: ThreatCategory.DataExfiltration,
    severity: Severity.High,
    pattern: /(?:fetch|axios)(?:\.(?:get|post|put|delete|patch))?\s*\([^)]*(?:password|token|secret|key|credential)/i,
    description: 'Sensitive data in network request detected',
    suggestion: 'Never include sensitive data in URL parameters or logs',
  },
  {
    id: 'exfil-xmlhttprequest',
    name: 'XMLHttpRequest with Credentials',
    category: ThreatCategory.DataExfiltration,
    severity: Severity.High,
    pattern: /XMLHttpRequest.*withCredentials\s*=\s*true/i,
    description: 'XHR with credentials enabled',
    suggestion: 'Use proper authentication headers and CORS policies',
  },
  {
    id: 'exfil-websocket',
    name: 'WebSocket Data Send',
    category: ThreatCategory.DataExfiltration,
    severity: Severity.Medium,
    pattern: /websocket.*\.send\s*\([^)]*(?:password|token|secret|key)/i,
    description: 'WebSocket sending sensitive data',
    suggestion: 'Encrypt sensitive data before WebSocket transmission',
  },
  {
    id: 'exfil-base64',
    name: 'Base64 Encoding of Data',
    category: ThreatCategory.DataExfiltration,
    severity: Severity.Medium,
    pattern: /btoa\s*\([^)]*(?:password|token|secret|key|credential)/i,
    description: 'Base64 encoding sensitive data before transmission',
    suggestion: 'Review need for encoding - may indicate exfiltration',
  },
  {
    id: 'exfil-dns',
    name: 'DNS Exfiltration Pattern',
    category: ThreatCategory.DataExfiltration,
    severity: Severity.High,
    pattern: /(?:dns|nslookup|dig).*?(?:password|token|secret|key)/i,
    description: 'DNS-based data exfiltration pattern',
    suggestion: 'Monitor DNS queries for suspicious patterns',
  },
  {
    id: 'exfil-url-param',
    name: 'URL Parameter Exfiltration',
    category: ThreatCategory.DataExfiltration,
    severity: Severity.Medium,
    pattern: /(?:password|token|secret|key|credential).*[=]{1}.+(?:&|\?|$)/i,
    description: 'Sensitive data in URL parameters detected',
    suggestion: 'Use POST body for sensitive data, never URL parameters',
  },

  // Obfuscation Patterns
  {
    id: 'obfuscated-code',
    name: 'Code Obfuscation',
    category: ThreatCategory.Obfuscation,
    severity: Severity.Medium,
    pattern: /\\x[0-9a-f]{2}|\\u[0-9a-f]{4}/i,
    description: 'Obfuscated code detected (hex/unicode escapes)',
    suggestion: 'Review code - obfuscation may hide malicious intent',
  },
  {
    id: 'obfuscation-base64',
    name: 'Suspicious Base64',
    category: ThreatCategory.Obfuscation,
    severity: Severity.Medium,
    pattern: /atob\(|btoa\(/i,
    description: 'Base64 encoding/decoding detected',
    suggestion: 'Verify the legitimacy of base64 operations',
  },
  {
    id: 'obfuscation-hex-variant',
    name: 'Hex Encoding Variants',
    category: ThreatCategory.Obfuscation,
    severity: Severity.Medium,
    pattern: /(?:0x[0-9a-f]+|%[0-9a-f]{2}){4,}/i,
    description: 'Multiple hex-encoded values detected',
    suggestion: 'Decode and review hex-encoded content',
  },
  {
    id: 'obfuscation-unicode',
    name: 'Unicode Escape Chains',
    category: ThreatCategory.Obfuscation,
    severity: Severity.Medium,
    pattern: /\\u[0-9a-f]{4}\\u[0-9a-f]{4}\\u[0-9a-f]{4}/i,
    description: 'Chain of unicode escapes detected',
    suggestion: 'Review the decoded unicode content',
  },
  {
    id: 'obfuscation-charcodeat',
    name: 'String.fromCharCode Chains',
    category: ThreatCategory.Obfuscation,
    severity: Severity.Medium,
    pattern: /String\.fromCharCode\s*\([^)]{20,}\)/i,
    description: 'String.fromCharCode chain detected',
    suggestion: 'Decode and review the constructed string',
  },
  {
    id: 'obfuscation-encoded-regex',
    name: 'Encoded Regex Pattern',
    category: ThreatCategory.Obfuscation,
    severity: Severity.Low,
    pattern: /new RegExp\s*\(\s*['"][^'"]{20,}['"]\s*\)/i,
    description: 'RegExp from string detected',
    suggestion: 'Review regex pattern construction',
  },

  // AI-Specific Patterns
  {
    id: 'ai-finetuning-data',
    name: 'Fine-tuning Data Exposure',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /(?:finetuning|fine[-_]?tuning|training[-_]?data).*[:=]{1}.+['"`]{1}/i,
    description: 'Possible fine-tuning data reference',
    suggestion: 'Never expose training data or model weights in prompts',
  },
  {
    id: 'ai-model-weights',
    name: 'Model Weight References',
    category: ThreatCategory.Other,
    severity: Severity.Critical,
    pattern: /(?:model[-_]?weight|parameter|tensor|checkpoint).*[:=]{1}.+['"`]{1}/i,
    description: 'Model weight or parameter reference detected',
    suggestion: 'Never expose model internals or weights',
  },
  {
    id: 'ai-training-path',
    name: 'Training Data Paths',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /(?:train[-_]?data|training[-_]?dataset|corpus).*[\\/][^\\s'"`]+/i,
    description: 'Training data path reference detected',
    suggestion: 'Never expose training data file paths',
  },
  {
    id: 'ai-prompt-template',
    name: 'Prompt Template Exposure',
    category: ThreatCategory.Other,
    severity: Severity.Medium,
    pattern: /(?:prompt[-_]?template|system[-_]?message|instruction[-_]?template).*[:=]{1}/i,
    description: 'Prompt template reference detected',
    suggestion: 'Keep prompt templates on server side only',
  },
  {
    id: 'ai-system-instruction',
    name: 'System Instruction Reference',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /(?:system[-_]?instruction|developer[-_]?message|assistant[-_]?prompt)/i,
    description: 'System instruction reference detected',
    suggestion: 'Never expose system-level instructions',
  },

  // Web Security Patterns
  {
    id: 'web-ssrf',
    name: 'Server-Side Request Forgery',
    category: ThreatCategory.Other,
    severity: Severity.Critical,
    pattern: /(?:fetch|axios|http\.request|request).*(?:localhost|127\.0\.0\.1|169\.254\.169\.254|metadata\.aws)/i,
    description: 'Possible SSRF attempt to internal services',
    suggestion: 'Validate and whitelist all external URLs',
  },
  {
    id: 'web-sql-injection',
    name: 'SQL Injection Pattern',
    category: ThreatCategory.Other,
    severity: Severity.Critical,
    pattern: /(?:SELECT|INSERT|UPDATE|DELETE|DROP).*FROM.*WHERE.*['"`].*['"`]/i,
    description: 'Possible SQL injection pattern',
    suggestion: 'Use parameterized queries and ORM libraries',
  },
  {
    id: 'web-xss',
    name: 'Cross-Site Scripting Pattern',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /(?:innerHTML|document\.write).*[+]=.*(?:user|input|param)/i,
    description: 'Possible XSS pattern detected',
    suggestion: 'Use textContent instead of innerHTML, sanitize input',
  },
  {
    id: 'web-csrf',
    name: 'CSRF Pattern',
    category: ThreatCategory.Other,
    severity: Severity.Medium,
    pattern: /(?:state changing|form submission).*(?:without csrf|missing csrf token)/i,
    description: 'Possible CSRF vulnerability',
    suggestion: 'Implement CSRF tokens for all state-changing operations',
  },
  {
    id: 'web-path-traversal',
    name: 'Path Traversal Pattern',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /(?:\.\.\/|\.\.\\|path.*\.\.|file.*\.\.)/i,
    description: 'Path traversal pattern detected',
    suggestion: 'Use path.normalize() and validate file paths',
  },
  {
    id: 'web-xxe',
    name: 'XML External Entity Pattern',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /<!DOCTYPE[^>]+ENTITY/i,
    description: 'Possible XXE vulnerability',
    suggestion: 'Disable DTD processing and use secure XML parsers',
  },
  {
    id: 'web-ssti',
    name: 'Server-Side Template Injection',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /(?:\{\{.*\}\}|<%.*%>|\$\{.*\}).*(?:user|input|param)/i,
    description: 'Possible SSTI pattern detected',
    suggestion: 'Use template engines with auto-escaping and sandboxing',
  },
  {
    id: 'web-ldap-injection',
    name: 'LDAP Injection Pattern',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /(?:\(|\)).*(?:\)|\()*=.*\)/i,
    description: 'Possible LDAP injection pattern',
    suggestion: 'Use proper LDAP parameter binding and validation',
  },
  {
    id: 'web-nosql-injection',
    name: 'NoSQL Injection Pattern',
    category: ThreatCategory.Other,
    severity: Severity.High,
    pattern: /\$[a-z_]+\s*:\s*\{?\s*\$[a-z_]+\s*:/i,
    description: 'Possible NoSQL injection (MongoDB) pattern',
    suggestion: 'Use proper query builders and input validation',
  },

  // Social Engineering Patterns
  {
    id: 'social-engineering',
    name: 'Social Engineering Pattern',
    category: ThreatCategory.SocialEngineering,
    severity: Severity.Medium,
    pattern: /(?:urgent|emergency|immediate).*(?:action|required|needed|verify)/i,
    description: 'Possible social engineering attempt',
    suggestion: 'Be cautious of urgent requests - verify through official channels',
  },
  {
    id: 'social-engineering-2',
    name: 'Phishing Pattern',
    category: ThreatCategory.SocialEngineering,
    severity: Severity.Medium,
    pattern: /(?:verify|confirm|update).*(?:account|password|credential|payment).*(?:immediately|now|urgent)/i,
    description: 'Phishing attempt pattern detected',
    suggestion: 'Never respond to unsolicited requests for credentials',
  },
  {
    id: 'social-engineering-3',
    name: 'Authority Impersonation',
    category: ThreatCategory.SocialEngineering,
    severity: Severity.Medium,
    pattern: /(?:as.*(?:ceo|cto|ciso|admin|manager|hr|security team)).*(?:request|need|require)/i,
    description: 'Authority impersonation attempt detected',
    suggestion: 'Verify sender identity through official channels',
  },
];

export class PatternLibrary {
  private patterns: Map<string, PatternRule>;

  constructor(customPatterns: PatternRule[] = []) {
    this.patterns = new Map();

    DEFAULT_PATTERNS.forEach((p) => this.addPattern(p));
    customPatterns.forEach((p) => this.addPattern(p));
  }

  addPattern(pattern: PatternRule): void {
    this.patterns.set(pattern.id, pattern);
  }

  getPattern(id: string): PatternRule | undefined {
    return this.patterns.get(id);
  }

  getAllPatterns(): PatternRule[] {
    return Array.from(this.patterns.values());
  }

  getPatternsByCategory(category: ThreatCategory): PatternRule[] {
    return this.getAllPatterns().filter((p) => p.category === category);
  }

  getPatternsBySeverity(severity: Severity): PatternRule[] {
    return this.getAllPatterns().filter((p) => p.severity === severity);
  }
}
